### ISSUE TITLE
Allow installing with HomeBrew

### ISSUE THREAD

**Issue by relaxnow** [veracode/scan_health#1]
For example by using GoReleaser: https://blog.alexwendland.com/2020-08-16-different-homebrew-formula-approaches-for-go-binaries/

**Comment by antfie** [comment]
https://github.com/veracode/homebrew-tap/pull/57

**Comment by antfie** [comment]
Brew support has now been added. Thank you for suggesting this enhancement.

```bash
brew tap veracode/tap
brew install scan_health
```

**Comment by relaxnow** [comment]
❤️  I love it. Thank you @antfie !
